// src/pages/UserDept/sqlTemplate.ts
const sqlTemplates = [
  {
    name: "用户",
    type: "insert",
    table: "`auth`.`SYS_AUTH_USER`",
    fieldMapping: [
      { tableField: "", dbField: "ID", defaultValue: null },
      { tableField: "userName", dbField: "USERNAME", defaultValue: null },
      {
        tableField: "",
        dbField: "PASSWORD",
        defaultValue: "d3424c55c24e5abec09cc15f89418d27",
      },
      {
        tableField: "chineseName",
        dbField: "CHINESE_NAME",
        defaultValue: null,
      },
      { tableField: "idcardNo", dbField: "IDCARD_NO", defaultValue: null },
      { tableField: "userName", dbField: "POLICE_CODE", defaultValue: null },
      { tableField: "deptCode", dbField: "DEPT_CODE", defaultValue: null },
      { tableField: "", dbField: "GENDER", defaultValue: null },
      { tableField: "", dbField: "EMAIL", defaultValue: null },
      { tableField: "phoneNo", dbField: "PHONE_NO", defaultValue: null },
      { tableField: "phoneNo", dbField: "SHORT_PHONE_NO", defaultValue: null },
      { tableField: "", dbField: "ADDRESS", defaultValue: null },
      { tableField: "", dbField: "REMARK", defaultValue: null },
      { tableField: "", dbField: "TYPE", defaultValue: "-1" },
      { tableField: "", dbField: "STATUS", defaultValue: "0" },
      {
        tableField: "",
        dbField: "WHEN_CREATED",
        defaultValue: "2024-05-07 20:29:22",
      },
      {
        tableField: "",
        dbField: "WHEN_MODIFIED",
        defaultValue: "2025-09-02 11:41:07",
      },
      { tableField: "", dbField: "WHO_CREATED", defaultValue: "917942" },
      { tableField: "", dbField: "WHO_MODIFIED", defaultValue: "92" },
      { tableField: "", dbField: "DELETED", defaultValue: "0" },
      { tableField: "", dbField: "POST", defaultValue: null },
      { tableField: "", dbField: "DEPT_PHONE_NO", defaultValue: null },
      { tableField: "", dbField: "DUTY", defaultValue: null },
      { tableField: "", dbField: "ENGLISH_NAME", defaultValue: null },
      { tableField: "", dbField: "BLOOD_TYPE", defaultValue: null },
      { tableField: "", dbField: "RECORDED_NO", defaultValue: null },
      { tableField: "", dbField: "INTERCOM_NO", defaultValue: null },
      { tableField: "", dbField: "POLICE_RANK", defaultValue: null },
      { tableField: "", dbField: "CLASSIFICATION", defaultValue: null },
      { tableField: "", dbField: "TOP_TIMES", defaultValue: null },
      { tableField: "", dbField: "RANK", defaultValue: null },
      { tableField: "", dbField: "BIRTHDAY", defaultValue: null },
      { tableField: "", dbField: "PATH", defaultValue: null },
      { tableField: "", dbField: "QUERYPATH", defaultValue: null },
      { tableField: "", dbField: "KTRW", defaultValue: "1" },
      { tableField: "", dbField: "APP_MSG_OFF", defaultValue: "1" },
      { tableField: "", dbField: "LOCK_STATUS", defaultValue: null },
      { tableField: "", dbField: "AVATAR_PATH", defaultValue: null },
      { tableField: "", dbField: "IS_DEPT_AUDIT", defaultValue: "0" },
      { tableField: "", dbField: "PLATFORM_ID", defaultValue: "2" },
      { tableField: "", dbField: "GXDWDM", defaultValue: null },
      { tableField: "", dbField: "IMEI", defaultValue: null },
      { tableField: "", dbField: "DEPT_EXPAND", defaultValue: null },
      { tableField: "", dbField: "LOGIN_TYPE", defaultValue: "0" },
      { tableField: "powerId", dbField: "POWER_ID", defaultValue: null },
      { tableField: "", dbField: "UNI_CODE", defaultValue: "TVJ38GK3" },
      { tableField: "", dbField: "ORDER_ADMIN", defaultValue: "0" },
      { tableField: "", dbField: "INVITATED_ID", defaultValue: null },
      { tableField: "", dbField: "INVITATED_TIME", defaultValue: null },
      { tableField: "", dbField: "XMBX_LOGIN_TIME", defaultValue: null },
      { tableField: "", dbField: "INITIAL", defaultValue: "A" },
      { tableField: "", dbField: "THIRD_ROLE", defaultValue: null },
      { tableField: "", dbField: "CSRKBM", defaultValue: null },
      { tableField: "", dbField: "POLICE_TYPE", defaultValue: null },
    ],
  },
  {
    name: "部门",
    type: "insert",
    table: "`auth`.`SYS_AUTH_DEPT`",
    fieldMapping: [
      { tableField: "", dbField: "ID", defaultValue: null },
      { tableField: "parentCode", dbField: "PARENT_CODE", defaultValue: null },
      { tableField: "", dbField: "SIMPLE_NAME", defaultValue: null },
      { tableField: "", dbField: "SUB_DEPT_CODE", defaultValue: null },
      { tableField: "", dbField: "PS_CODE", defaultValue: null },
      { tableField: "deptName", dbField: "DEPT_NAME", defaultValue: null },
      { tableField: "deptCode", dbField: "DEPT_CODE", defaultValue: null },
      { tableField: "", dbField: "AREA_CODE", defaultValue: null },
      { tableField: "", dbField: "INNER_CODE", defaultValue: null },
      {
        tableField: "",
        dbField: "WHEN_CREATED",
        defaultValue: "2024-04-26 18:18:18",
      },
      { tableField: "", dbField: "WHEN_MODIFIED", defaultValue: null },
      { tableField: "", dbField: "WHO_CREATED", defaultValue: "1" },
      { tableField: "", dbField: "WHO_MODIFIED", defaultValue: null },
      { tableField: "", dbField: "DELETED", defaultValue: "0" },
      { tableField: "deptLevel", dbField: "DEPT_LEVEL", defaultValue: null },
      { tableField: "", dbField: "CONCAT", defaultValue: null },
      { tableField: "", dbField: "TYPE", defaultValue: null },
      { tableField: "", dbField: "ADDRESS", defaultValue: null },
      { tableField: "", dbField: "TEL", defaultValue: null },
      { tableField: "", dbField: "TEXT", defaultValue: null },
      { tableField: "", dbField: "TOP_TIMES", defaultValue: null },
      { tableField: "", dbField: "RANK", defaultValue: null },
      { tableField: "", dbField: "JXH", defaultValue: "1" },
      { tableField: "", dbField: "PRILEVEL", defaultValue: null },
      { tableField: "", dbField: "OLD_DEPT_CODE", defaultValue: null },
      { tableField: "", dbField: "AUDIT_TYPE", defaultValue: "1" },
      { tableField: "", dbField: "UNFULFILLED_MESSAGE", defaultValue: "1" },
      { tableField: "", dbField: "UNSIGNED_MESSAGE", defaultValue: "1" },
      { tableField: "", dbField: "UNSCHEDULED_MESSAGE", defaultValue: "1" },
      { tableField: "", dbField: "PLATFORM_ID", defaultValue: null },
      { tableField: "", dbField: "CODE_RULE_ID", defaultValue: null },
      { tableField: "", dbField: "CUSTOMER", defaultValue: null },
      { tableField: "", dbField: "DEPT_UNI_CODE", defaultValue: null },
      { tableField: "", dbField: "ENABLED", defaultValue: null },
      { tableField: "", dbField: "TOP_LIMIT", defaultValue: null },
      { tableField: "", dbField: "RELATED_WORK_SWITCH", defaultValue: "0" },
    ],
  },
  {
  name: "管辖单位",
  type: "insert",
  table: "`OBJECT_PLATFORM`.`SYS_GXDW`",
  fieldMapping: [
    { tableField: "", dbField: "ID", defaultValue: null },
    { tableField: "parentCode", dbField: "PARENTDM", defaultValue: null },
    { tableField: "deptName", dbField: "GXDWJC", defaultValue: null },
    { tableField: "", dbField: "FJDM", defaultValue: "需要自己指定了" },
    { tableField: "deptCode", dbField: "PCSDM", defaultValue: null },
    { tableField: "deptName", dbField: "GXDWQC", defaultValue: null },
    { tableField: "", dbField: "ZRQDM", defaultValue: null },
    { tableField: "deptCode", dbField: "GXDWDM", defaultValue: "460100060000" },
    { tableField: "", dbField: "SZDJ", defaultValue: "3" },
    { tableField: "", dbField: "LON", defaultValue: null },
    { tableField: "", dbField: "LAT", defaultValue: null },
    { tableField: "", dbField: "WHEN_MODIFIED", defaultValue: "2024-04-28 11:53:04" },
    { tableField: "", dbField: "SJDM", defaultValue: null },
    { tableField: "", dbField: "ENABLED", defaultValue: null }
  ]
},
];

export default sqlTemplates;
